config/routes.rb
Rails.application.routes.draw do
  root 'parses#index'
  resources :parses
  resources :links
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
end

app/models/parse.rb
class Parse < ApplicationRecord
  validates :text, presence:true, length: { maximum: 5000 }

  PARAMETERS = %w[c_plus_plus c_sharp vb c java ruby rails physics chemistry mathematics
    social_science history science geography bus train rickshaw bike car]

  PARAMETERS.each do |parameter|
    define_method(:"count_#{parameter}") do
      text.gsub('.','').gsub('!','').gsub(',','').gsub(' ','').downcase.scan(/#{parse_string(parameter)}/).length
    end
  end

  def parse_string(parameter)
    if parameter == "c_plus_plus"
      return 'c++'
    elsif parameter == 'c_sharp'
      return'c#'
    elsif parameter == 'social_science'
      return 'socialscience'
    else
      return parameter
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  
  def index
    @links = Link.all
  end
  
  def new
    @link = Link.new
  end

end

app/controllers/parses_controller.rb
class ParsesController < ApplicationController
  
  def index
    @parses = Parse.order('created_at DESC')
  end
  
  def new
    @parse = Parse.new
  end
  
  def create
    @parse = Parse.create(parse_params)
    if @parse.save
      redirect_to @parse
    else
      redirect_to :back, notice: @parse.errors
    end
  end

  def show
    @parse = Parse.find(params[:id])
  end


  private
  def parse_params
    params.require(:parse).permit(:text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/parses_helper.rb
module ParsesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/parses/_form.html.erb
<center>
  <h1>String Parsing</h1>
  <%= form_for Parse.new do |f|%>
    <%= f.label :Enter_string_to_parse %><br>
    <%= f.text_area :text, size: '100' %><br>
    <%= f.submit %>
  <% end %>
</center> 

app/views/parses/index.html.erb
<%= render 'form' %>
<% @parses.each do |parse|%>
  <%= link_to truncate(parse.text, length: 20), parse_path(parse)%>
  <p><%= "C= #{parse.count_c}" unless parse.count_c.zero? %></p>
  <p><%= "Java= #{parse.count_java}"  unless parse.count_java.zero?  %></p>
  <p><%= "C# = #{parse.count_c_sharp}" unless parse.count_c_sharp.zero?  %></p>
  <p><%= "C++ = #{parse.count_c_plus_plus}" unless parse.count_c_plus_plus.zero?  %></p>
  <p><%= "VB = #{parse.count_vb}" unless parse.count_vb.zero?  %></p>
  <p><%= "Ruby = #{parse.count_ruby}" unless parse.count_ruby.zero?  %></p>
  <p><%= "Rails = #{parse.count_rails}" unless parse.count_rails.zero?  %></p>
  <p><%= "Physics = #{parse.count_physics}" unless parse.count_physics.zero?  %></p>
  <p><%= "Chemistry = #{parse.count_chemistry}" unless parse.count_chemistry.zero?  %></p>
  <p><%= "Mathematics = #{parse.count_mathematics}" unless parse.count_mathematics.zero?  %></p>
  <p><%= "Social Science = #{parse.count_social_science}" unless parse.count_social_science.zero?  %></p>
  <p><%= "Science = #{parse.count_science}" unless parse.count_science.zero?  %></p>
  <p><%= "History = #{parse.count_history}" unless parse.count_history.zero?  %></p>
  <p><%= "Geography = #{parse.count_geography}" unless parse.count_geography.zero? %></p>
  <p><%= "Bus = #{parse.count_bus}" unless parse.count_bus.zero? %></p>
  <p><%= "Train = #{parse.count_train}" unless parse.count_train.zero? %></p>
  <p><%= "Rickshaw = #{parse.count_rickshaw}" unless parse.count_rickshaw.zero? %></p>
  <p><%= "Bike = #{parse.count_bike}" unless parse.count_bike.zero?%></p>
  <p><%= "Car = #{parse.count_car}" unless parse.count_car.zero?%></p>
  <hr>
<% end %>

app/views/parses/new.html.erb
<%= render 'form' %>

app/views/parses/show.html.erb
<h1> Parsed String </h1>
<%= @parse.text%>
<p><%= "C= #{@parse.count_c}" unless @parse.count_c.zero? %></p>
<p><%= "Java= #{@parse.count_java}"  unless @parse.count_java.zero?  %></p>
<p><%= "C# = #{@parse.count_c_sharp}" unless @parse.count_c_sharp.zero?  %></p>
<p><%= "C++ = #{@parse.count_c_plus_plus}" unless @parse.count_c_plus_plus.zero?  %></p>
<p><%= "VB = #{@parse.count_vb}" unless @parse.count_vb.zero?  %></p>
<p><%= "Ruby = #{@parse.count_ruby}" unless @parse.count_ruby.zero?  %></p>
<p><%= "Rails = #{@parse.count_rails}" unless @parse.count_rails.zero?  %></p>
<p><%= "Physics = #{@parse.count_physics}" unless @parse.count_physics.zero?  %></p>
<p><%= "Chemistry = #{@parse.count_chemistry}" unless @parse.count_chemistry.zero?  %></p>
<p><%= "Mathematics = #{@parse.count_mathematics}" unless @parse.count_mathematics.zero?  %></p>
<p><%= "Social Science = #{@parse.count_social_science}" unless @parse.count_social_science.zero?  %></p> 
<p><%= "Science = #{@parse.count_science}" unless @parse.count_science.zero?  %></p>
<p><%= "History = #{@parse.count_history}" unless @parse.count_history.zero?  %></p>
<p><%= "Geography = #{@parse.count_geography}" unless @parse.count_geography.zero? %></p>
<p><%= "Bus = #{@parse.count_bus}" unless @parse.count_bus.zero? %></p>
<p><%= "Train = #{@parse.count_train}" unless @parse.count_train.zero? %></p>
<p><%= "Rickshaw = #{@parse.count_rickshaw}" unless @parse.count_rickshaw.zero? %></p>
<p><%= "Bike = #{@parse.count_bike}" unless @parse.count_bike.zero?%></p>
<p><%= "Car = #{@parse.count_car}" unless @parse.count_car.zero?%></p>
<%= link_to "Home", parses_path%>